# Show Foreign Keys
SELECT KEY_COLUMN_USAGE.TABLE_SCHEMA
		 , TABLE_NAME
		 , COLUMN_NAME
		 , CONSTRAINT_NAME
		 , REFERENCED_TABLE_NAME
		 , REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TRUE
	AND KEY_COLUMN_USAGE.TABLE_SCHEMA IN('db_youfilter', 'insights', 'statistics')
	AND KEY_COLUMN_USAGE.REFERENCED_COLUMN_NAME IS NOT NULL
;
